export const weatherMap = {
	0: { texte: "Ciel dégagé", icone: ""},
	1: { texte: "Plutôt dégagé", icone: ""},
	2: { texte: "Partiellement nuageux", icone: ""},
	3: { texte: "Couvert", icone: ""},
	45: { texte: "Brouillard", icone: ""},
	48: { texte: "Brouillard givrant", icone: ""},
	51: { texte: "Bruine légère", icone: ""},
	53: { texte: "Bruine modérée", icone: ""},
	55: { texte: "Bruine dense", icone: ""},
	56: { texte: "Bruine glaciale légère", icone: ""},
	57: { texte: "Bruine glaciale dense", icone: ""},
	61: { texte: "Pluie légère", icone: ""},
	63: { texte: "Pluie modérée", icone: ""},
	65: { texte: "Forte pluie", icone: ""},
	66: { texte: "Pluie verglaçante", icone: ""},
	67: { texte: "Forte pluie verglaçante", icone: ""},
	71: { texte: "Chutes de neige légères", icone: ""},
	73: { texte: "Chutes de neige modérées", icone: ""},
	75: { texte: "Fortes chutes de neige", icone: ""},
	77: { texte: "Grains de neige", icone: ""},
	80: { texte: "Averses de pluie légères", icone: ""},
	81: { texte: "Averses de pluie modérées", icone: ""},
	82: { texte: "Fortes averses de pluie", icone: ""},
	85: { texte: "Averses de neige", icone: ""},
	86: { texte: "Fortes averses de neige", icone: ""},
	95: { texte: "Orage", icone: ""},
	96: { texte: "Orage avec grêle", icone: ""},
	99: { texte: "Orage avec grêle abondante", icone: ""}
};